//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ProxyCacheDBCiudad.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class Voto implements java.lang.Cloneable,
                             java.io.Serializable
{
    public String documentoVotante;

    public int candidatoId;

    public int mesaId;

    public String fechaHora;

    public Voto()
    {
        this.documentoVotante = "";
        this.fechaHora = "";
    }

    public Voto(String documentoVotante, int candidatoId, int mesaId, String fechaHora)
    {
        this.documentoVotante = documentoVotante;
        this.candidatoId = candidatoId;
        this.mesaId = mesaId;
        this.fechaHora = fechaHora;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Voto r = null;
        if(rhs instanceof Voto)
        {
            r = (Voto)rhs;
        }

        if(r != null)
        {
            if(this.documentoVotante != r.documentoVotante)
            {
                if(this.documentoVotante == null || r.documentoVotante == null || !this.documentoVotante.equals(r.documentoVotante))
                {
                    return false;
                }
            }
            if(this.candidatoId != r.candidatoId)
            {
                return false;
            }
            if(this.mesaId != r.mesaId)
            {
                return false;
            }
            if(this.fechaHora != r.fechaHora)
            {
                if(this.fechaHora == null || r.fechaHora == null || !this.fechaHora.equals(r.fechaHora))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotingSystem::Voto");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, documentoVotante);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, candidatoId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mesaId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fechaHora);
        return h_;
    }

    public Voto clone()
    {
        Voto c = null;
        try
        {
            c = (Voto)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.documentoVotante);
        ostr.writeInt(this.candidatoId);
        ostr.writeInt(this.mesaId);
        ostr.writeString(this.fechaHora);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.documentoVotante = istr.readString();
        this.candidatoId = istr.readInt();
        this.mesaId = istr.readInt();
        this.fechaHora = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Voto v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Voto ice_read(com.zeroc.Ice.InputStream istr)
    {
        Voto v = new Voto();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Voto> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Voto v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Voto> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Voto.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Voto _nullMarshalValue = new Voto();

    /** @hidden */
    public static final long serialVersionUID = -6380919641369540982L;
}
