//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MainServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class AlertaInfo implements java.lang.Cloneable,
                                   java.io.Serializable
{
    public int id;

    public String tipo;

    public String mensaje;

    public String fecha;

    public AlertaInfo()
    {
        this.tipo = "";
        this.mensaje = "";
        this.fecha = "";
    }

    public AlertaInfo(int id, String tipo, String mensaje, String fecha)
    {
        this.id = id;
        this.tipo = tipo;
        this.mensaje = mensaje;
        this.fecha = fecha;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        AlertaInfo r = null;
        if(rhs instanceof AlertaInfo)
        {
            r = (AlertaInfo)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.tipo != r.tipo)
            {
                if(this.tipo == null || r.tipo == null || !this.tipo.equals(r.tipo))
                {
                    return false;
                }
            }
            if(this.mensaje != r.mensaje)
            {
                if(this.mensaje == null || r.mensaje == null || !this.mensaje.equals(r.mensaje))
                {
                    return false;
                }
            }
            if(this.fecha != r.fecha)
            {
                if(this.fecha == null || r.fecha == null || !this.fecha.equals(r.fecha))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotingSystem::AlertaInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tipo);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mensaje);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fecha);
        return h_;
    }

    public AlertaInfo clone()
    {
        AlertaInfo c = null;
        try
        {
            c = (AlertaInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeString(this.tipo);
        ostr.writeString(this.mensaje);
        ostr.writeString(this.fecha);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.tipo = istr.readString();
        this.mensaje = istr.readString();
        this.fecha = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, AlertaInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public AlertaInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        AlertaInfo v = new AlertaInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<AlertaInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, AlertaInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<AlertaInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(AlertaInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final AlertaInfo _nullMarshalValue = new AlertaInfo();

    /** @hidden */
    public static final long serialVersionUID = -6481840070427358561L;
}
