# Configuración del nodo IceGrid
Ice.Default.Locator=IceGrid/Locator:tcp -h localhost -p 4061
IceGrid.Node.Name=node1
IceGrid.Node.Data=db/node
IceGrid.Node.Endpoints=tcp -h localhost

# Configuración de seguridad
Ice.ACM.Timeout=60
Ice.ThreadPool.Server.Size=4
Ice.ThreadPool.Server.SizeMax=8
Ice.MessageSizeMax=20480

# Configuración de registro
Ice.Default.Protocol=tcp
Ice.IPv6=0 