# Configuración del registro IceGrid
IceGrid.Registry.Client.Endpoints=tcp -h localhost -p 4061
IceGrid.Registry.Server.Endpoints=tcp -h localhost
IceGrid.Registry.Internal.Endpoints=tcp -h localhost
IceGrid.Registry.Data=db/registry
IceGrid.Registry.DynamicRegistration=1

# Configuración de seguridad
Ice.ACM.Timeout=60
Ice.ThreadPool.Server.Size=4
Ice.ThreadPool.Server.SizeMax=8
Ice.MessageSizeMax=20480

# Configuración general
Ice.Default.Protocol=tcp
Ice.IPv6=0 