//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Portal.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.interfaces;

/** @hidden */
public class _AccesoDatosPrxI extends com.zeroc.Ice._ObjectPrxI implements AccesoDatosPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
