//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Votacion.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.interfaces;

public interface MesaVotacion extends com.zeroc.Ice.Object
{
    boolean registrarVoto(String cedula, String candidato, String mesa, com.zeroc.Ice.Current current)
        throws VotacionException;

    String obtenerResultadosMesa(String mesa, com.zeroc.Ice.Current current);

    String listarMesas(com.zeroc.Ice.Current current);

    boolean validarVotante(String cedula, String mesa, com.zeroc.Ice.Current current)
        throws VotacionException;

    String obtenerEstadisticas(com.zeroc.Ice.Current current);

    boolean verificarCedula(String cedula, com.zeroc.Ice.Current current)
        throws VotacionException;

    String obtenerMesaAsignada(String cedula, com.zeroc.Ice.Current current)
        throws VotacionException;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::com::sistemaelectoral::interfaces::MesaVotacion"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::com::sistemaelectoral::interfaces::MesaVotacion";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_registrarVoto(MesaVotacion obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_cedula;
        String iceP_candidato;
        String iceP_mesa;
        iceP_cedula = istr.readString();
        iceP_candidato = istr.readString();
        iceP_mesa = istr.readString();
        inS.endReadParams();
        boolean ret = obj.registrarVoto(iceP_cedula, iceP_candidato, iceP_mesa, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerResultadosMesa(MesaVotacion obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_mesa;
        iceP_mesa = istr.readString();
        inS.endReadParams();
        String ret = obj.obtenerResultadosMesa(iceP_mesa, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_listarMesas(MesaVotacion obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String ret = obj.listarMesas(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_validarVotante(MesaVotacion obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_cedula;
        String iceP_mesa;
        iceP_cedula = istr.readString();
        iceP_mesa = istr.readString();
        inS.endReadParams();
        boolean ret = obj.validarVotante(iceP_cedula, iceP_mesa, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerEstadisticas(MesaVotacion obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String ret = obj.obtenerEstadisticas(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_verificarCedula(MesaVotacion obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_cedula;
        iceP_cedula = istr.readString();
        inS.endReadParams();
        boolean ret = obj.verificarCedula(iceP_cedula, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_obtenerMesaAsignada(MesaVotacion obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_cedula;
        iceP_cedula = istr.readString();
        inS.endReadParams();
        String ret = obj.obtenerMesaAsignada(iceP_cedula, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "listarMesas",
        "obtenerEstadisticas",
        "obtenerMesaAsignada",
        "obtenerResultadosMesa",
        "registrarVoto",
        "validarVotante",
        "verificarCedula"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 1:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 4:
            {
                return _iceD_listarMesas(this, in, current);
            }
            case 5:
            {
                return _iceD_obtenerEstadisticas(this, in, current);
            }
            case 6:
            {
                return _iceD_obtenerMesaAsignada(this, in, current);
            }
            case 7:
            {
                return _iceD_obtenerResultadosMesa(this, in, current);
            }
            case 8:
            {
                return _iceD_registrarVoto(this, in, current);
            }
            case 9:
            {
                return _iceD_validarVotante(this, in, current);
            }
            case 10:
            {
                return _iceD_verificarCedula(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
