//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Votacion.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.interfaces;

public class VotacionException extends com.zeroc.Ice.UserException
{
    public VotacionException()
    {
        this.reason = "";
    }

    public VotacionException(Throwable cause)
    {
        super(cause);
        this.reason = "";
    }

    public VotacionException(String reason)
    {
        this.reason = reason;
    }

    public VotacionException(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::com::sistemaelectoral::interfaces::VotacionException";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::com::sistemaelectoral::interfaces::VotacionException", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -7457411976148726960L;
}
