//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ProxyCacheDBCiudad.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class Zona implements java.lang.Cloneable,
                             java.io.Serializable
{
    public int id;

    public String nombre;

    public String codigo;

    public Zona()
    {
        this.nombre = "";
        this.codigo = "";
    }

    public Zona(int id, String nombre, String codigo)
    {
        this.id = id;
        this.nombre = nombre;
        this.codigo = codigo;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Zona r = null;
        if(rhs instanceof Zona)
        {
            r = (Zona)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.nombre != r.nombre)
            {
                if(this.nombre == null || r.nombre == null || !this.nombre.equals(r.nombre))
                {
                    return false;
                }
            }
            if(this.codigo != r.codigo)
            {
                if(this.codigo == null || r.codigo == null || !this.codigo.equals(r.codigo))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotingSystem::Zona");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nombre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, codigo);
        return h_;
    }

    public Zona clone()
    {
        Zona c = null;
        try
        {
            c = (Zona)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeString(this.nombre);
        ostr.writeString(this.codigo);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.nombre = istr.readString();
        this.codigo = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Zona v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Zona ice_read(com.zeroc.Ice.InputStream istr)
    {
        Zona v = new Zona();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Zona> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Zona v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Zona> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Zona.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Zona _nullMarshalValue = new Zona();

    /** @hidden */
    public static final long serialVersionUID = 1477971783508752803L;
}
