//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MainServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class Estadisticas implements java.lang.Cloneable,
                                     java.io.Serializable
{
    public int totalVotos;

    public int totalMesas;

    public int mesasActivas;

    public Estadisticas()
    {
    }

    public Estadisticas(int totalVotos, int totalMesas, int mesasActivas)
    {
        this.totalVotos = totalVotos;
        this.totalMesas = totalMesas;
        this.mesasActivas = mesasActivas;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Estadisticas r = null;
        if(rhs instanceof Estadisticas)
        {
            r = (Estadisticas)rhs;
        }

        if(r != null)
        {
            if(this.totalVotos != r.totalVotos)
            {
                return false;
            }
            if(this.totalMesas != r.totalMesas)
            {
                return false;
            }
            if(this.mesasActivas != r.mesasActivas)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotingSystem::Estadisticas");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalVotos);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalMesas);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mesasActivas);
        return h_;
    }

    public Estadisticas clone()
    {
        Estadisticas c = null;
        try
        {
            c = (Estadisticas)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.totalVotos);
        ostr.writeInt(this.totalMesas);
        ostr.writeInt(this.mesasActivas);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.totalVotos = istr.readInt();
        this.totalMesas = istr.readInt();
        this.mesasActivas = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Estadisticas v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Estadisticas ice_read(com.zeroc.Ice.InputStream istr)
    {
        Estadisticas v = new Estadisticas();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Estadisticas> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Estadisticas v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(12);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<Estadisticas> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(Estadisticas.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Estadisticas _nullMarshalValue = new Estadisticas();

    /** @hidden */
    public static final long serialVersionUID = -2002001345L;
}
