//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MainServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class LoteVotos implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public Voto[] votos;

    public LoteVotos()
    {
    }

    public LoteVotos(Voto[] votos)
    {
        this.votos = votos;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LoteVotos r = null;
        if(rhs instanceof LoteVotos)
        {
            r = (LoteVotos)rhs;
        }

        if(r != null)
        {
            if(!java.util.Arrays.equals(this.votos, r.votos))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotingSystem::LoteVotos");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, votos);
        return h_;
    }

    public LoteVotos clone()
    {
        LoteVotos c = null;
        try
        {
            c = (LoteVotos)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        VotoSeqHelper.write(ostr, this.votos);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.votos = VotoSeqHelper.read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, LoteVotos v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public LoteVotos ice_read(com.zeroc.Ice.InputStream istr)
    {
        LoteVotos v = new LoteVotos();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LoteVotos> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, LoteVotos v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<LoteVotos> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(LoteVotos.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final LoteVotos _nullMarshalValue = new LoteVotos();

    /** @hidden */
    public static final long serialVersionUID = -7639495354922455242L;
}
