//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MainServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public interface MainServerPrx extends com.zeroc.Ice.ObjectPrx
{
    default MesaInfo[] obtenerEstadoMesas()
    {
        return obtenerEstadoMesas(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MesaInfo[] obtenerEstadoMesas(java.util.Map<String, String> context)
    {
        return _iceI_obtenerEstadoMesasAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<MesaInfo[]> obtenerEstadoMesasAsync()
    {
        return _iceI_obtenerEstadoMesasAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MesaInfo[]> obtenerEstadoMesasAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerEstadoMesasAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MesaInfo[]> _iceI_obtenerEstadoMesasAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MesaInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerEstadoMesas", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     MesaInfo[] ret;
                     ret = MesaInfoListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default MesaInfo obtenerEstadoMesa(int mesaId)
    {
        return obtenerEstadoMesa(mesaId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MesaInfo obtenerEstadoMesa(int mesaId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerEstadoMesaAsync(mesaId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<MesaInfo> obtenerEstadoMesaAsync(int mesaId)
    {
        return _iceI_obtenerEstadoMesaAsync(mesaId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MesaInfo> obtenerEstadoMesaAsync(int mesaId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerEstadoMesaAsync(mesaId, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MesaInfo> _iceI_obtenerEstadoMesaAsync(int iceP_mesaId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MesaInfo> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerEstadoMesa", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                 }, istr -> {
                     MesaInfo ret;
                     ret = MesaInfo.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void actualizarEstadoMesa(int mesaId, String estado)
    {
        actualizarEstadoMesa(mesaId, estado, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void actualizarEstadoMesa(int mesaId, String estado, java.util.Map<String, String> context)
    {
        _iceI_actualizarEstadoMesaAsync(mesaId, estado, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> actualizarEstadoMesaAsync(int mesaId, String estado)
    {
        return _iceI_actualizarEstadoMesaAsync(mesaId, estado, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> actualizarEstadoMesaAsync(int mesaId, String estado, java.util.Map<String, String> context)
    {
        return _iceI_actualizarEstadoMesaAsync(mesaId, estado, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param iceP_estado -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_actualizarEstadoMesaAsync(int iceP_mesaId, String iceP_estado, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "actualizarEstadoMesa", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                     ostr.writeString(iceP_estado);
                 }, null);
        return f;
    }

    default int obtenerTotalVotos()
    {
        return obtenerTotalVotos(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int obtenerTotalVotos(java.util.Map<String, String> context)
    {
        return _iceI_obtenerTotalVotosAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> obtenerTotalVotosAsync()
    {
        return _iceI_obtenerTotalVotosAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> obtenerTotalVotosAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerTotalVotosAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_obtenerTotalVotosAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerTotalVotos", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int obtenerVotosMesa(int mesaId)
    {
        return obtenerVotosMesa(mesaId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int obtenerVotosMesa(int mesaId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerVotosMesaAsync(mesaId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> obtenerVotosMesaAsync(int mesaId)
    {
        return _iceI_obtenerVotosMesaAsync(mesaId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> obtenerVotosMesaAsync(int mesaId, java.util.Map<String, String> context)
    {
        return _iceI_obtenerVotosMesaAsync(mesaId, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_obtenerVotosMesaAsync(int iceP_mesaId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerVotosMesa", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default String generarResultadosParciales(int mesaId)
    {
        return generarResultadosParciales(mesaId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String generarResultadosParciales(int mesaId, java.util.Map<String, String> context)
    {
        return _iceI_generarResultadosParcialesAsync(mesaId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> generarResultadosParcialesAsync(int mesaId)
    {
        return _iceI_generarResultadosParcialesAsync(mesaId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> generarResultadosParcialesAsync(int mesaId, java.util.Map<String, String> context)
    {
        return _iceI_generarResultadosParcialesAsync(mesaId, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_generarResultadosParcialesAsync(int iceP_mesaId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "generarResultadosParciales", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String generarResultadosFinales()
    {
        return generarResultadosFinales(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String generarResultadosFinales(java.util.Map<String, String> context)
    {
        return _iceI_generarResultadosFinalesAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> generarResultadosFinalesAsync()
    {
        return _iceI_generarResultadosFinalesAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> generarResultadosFinalesAsync(java.util.Map<String, String> context)
    {
        return _iceI_generarResultadosFinalesAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_generarResultadosFinalesAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "generarResultadosFinales", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default AlertaInfo[] obtenerAlertas()
    {
        return obtenerAlertas(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default AlertaInfo[] obtenerAlertas(java.util.Map<String, String> context)
    {
        return _iceI_obtenerAlertasAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<AlertaInfo[]> obtenerAlertasAsync()
    {
        return _iceI_obtenerAlertasAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<AlertaInfo[]> obtenerAlertasAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerAlertasAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<AlertaInfo[]> _iceI_obtenerAlertasAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<AlertaInfo[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerAlertas", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     AlertaInfo[] ret;
                     ret = AlertaInfoListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void registrarAlerta(AlertaInfo alerta)
    {
        registrarAlerta(alerta, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registrarAlerta(AlertaInfo alerta, java.util.Map<String, String> context)
    {
        _iceI_registrarAlertaAsync(alerta, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registrarAlertaAsync(AlertaInfo alerta)
    {
        return _iceI_registrarAlertaAsync(alerta, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registrarAlertaAsync(AlertaInfo alerta, java.util.Map<String, String> context)
    {
        return _iceI_registrarAlertaAsync(alerta, context, false);
    }

    /**
     * @hidden
     * @param iceP_alerta -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registrarAlertaAsync(AlertaInfo iceP_alerta, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registrarAlerta", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     AlertaInfo.ice_write(ostr, iceP_alerta);
                 }, null);
        return f;
    }

    default void limpiarAlertas()
    {
        limpiarAlertas(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void limpiarAlertas(java.util.Map<String, String> context)
    {
        _iceI_limpiarAlertasAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> limpiarAlertasAsync()
    {
        return _iceI_limpiarAlertasAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> limpiarAlertasAsync(java.util.Map<String, String> context)
    {
        return _iceI_limpiarAlertasAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_limpiarAlertasAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "limpiarAlertas", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void cerrarVotacion()
    {
        cerrarVotacion(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void cerrarVotacion(java.util.Map<String, String> context)
    {
        _iceI_cerrarVotacionAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> cerrarVotacionAsync()
    {
        return _iceI_cerrarVotacionAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> cerrarVotacionAsync(java.util.Map<String, String> context)
    {
        return _iceI_cerrarVotacionAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_cerrarVotacionAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "cerrarVotacion", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void cerrarMesa(int mesaId)
    {
        cerrarMesa(mesaId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void cerrarMesa(int mesaId, java.util.Map<String, String> context)
    {
        _iceI_cerrarMesaAsync(mesaId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> cerrarMesaAsync(int mesaId)
    {
        return _iceI_cerrarMesaAsync(mesaId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> cerrarMesaAsync(int mesaId, java.util.Map<String, String> context)
    {
        return _iceI_cerrarMesaAsync(mesaId, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_cerrarMesaAsync(int iceP_mesaId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "cerrarMesa", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                 }, null);
        return f;
    }

    default boolean validarMesaActiva(int mesaId)
    {
        return validarMesaActiva(mesaId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean validarMesaActiva(int mesaId, java.util.Map<String, String> context)
    {
        return _iceI_validarMesaActivaAsync(mesaId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> validarMesaActivaAsync(int mesaId)
    {
        return _iceI_validarMesaActivaAsync(mesaId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> validarMesaActivaAsync(int mesaId, java.util.Map<String, String> context)
    {
        return _iceI_validarMesaActivaAsync(mesaId, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_validarMesaActivaAsync(int iceP_mesaId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "validarMesaActiva", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default String obtenerEstadisticas()
    {
        return obtenerEstadisticas(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String obtenerEstadisticas(java.util.Map<String, String> context)
    {
        return _iceI_obtenerEstadisticasAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> obtenerEstadisticasAsync()
    {
        return _iceI_obtenerEstadisticasAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> obtenerEstadisticasAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerEstadisticasAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_obtenerEstadisticasAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerEstadisticas", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default int contarMesasActivas()
    {
        return contarMesasActivas(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int contarMesasActivas(java.util.Map<String, String> context)
    {
        return _iceI_contarMesasActivasAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> contarMesasActivasAsync()
    {
        return _iceI_contarMesasActivasAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> contarMesasActivasAsync(java.util.Map<String, String> context)
    {
        return _iceI_contarMesasActivasAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_contarMesasActivasAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "contarMesasActivas", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MainServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MainServerPrx.class, _MainServerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MainServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MainServerPrx.class, _MainServerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MainServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MainServerPrx.class, _MainServerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MainServerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MainServerPrx.class, _MainServerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MainServerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MainServerPrx.class, _MainServerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MainServerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MainServerPrx.class, _MainServerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MainServerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (MainServerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MainServerPrx ice_adapterId(String newAdapterId)
    {
        return (MainServerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MainServerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (MainServerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MainServerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (MainServerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MainServerPrx ice_invocationTimeout(int newTimeout)
    {
        return (MainServerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MainServerPrx ice_connectionCached(boolean newCache)
    {
        return (MainServerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MainServerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (MainServerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MainServerPrx ice_secure(boolean b)
    {
        return (MainServerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MainServerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (MainServerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MainServerPrx ice_preferSecure(boolean b)
    {
        return (MainServerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MainServerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (MainServerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MainServerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (MainServerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MainServerPrx ice_collocationOptimized(boolean b)
    {
        return (MainServerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MainServerPrx ice_twoway()
    {
        return (MainServerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MainServerPrx ice_oneway()
    {
        return (MainServerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MainServerPrx ice_batchOneway()
    {
        return (MainServerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MainServerPrx ice_datagram()
    {
        return (MainServerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MainServerPrx ice_batchDatagram()
    {
        return (MainServerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MainServerPrx ice_compress(boolean co)
    {
        return (MainServerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MainServerPrx ice_timeout(int t)
    {
        return (MainServerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MainServerPrx ice_connectionId(String connectionId)
    {
        return (MainServerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default MainServerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (MainServerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::VotingSystem::MainServer";
    }
}
