//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MainServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

/**
 * Helper class for marshaling/unmarshaling MesaInfoList.
 **/
public final class MesaInfoListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, MesaInfo[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                MesaInfo.ice_write(ostr, v[i0]);
            }
        }
    }

    public static MesaInfo[] read(com.zeroc.Ice.InputStream istr)
    {
        final MesaInfo[] v;
        final int len0 = istr.readAndCheckSeqSize(16);
        v = new MesaInfo[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = MesaInfo.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<MesaInfo[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, MesaInfo[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            MesaInfoListHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<MesaInfo[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            MesaInfo[] v;
            v = MesaInfoListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
