//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MainServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public interface StationNotifierPrx extends com.zeroc.Ice.ObjectPrx
{
    default void notificarVoto(int mesaId, String timestamp)
    {
        notificarVoto(mesaId, timestamp, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notificarVoto(int mesaId, String timestamp, java.util.Map<String, String> context)
    {
        _iceI_notificarVotoAsync(mesaId, timestamp, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notificarVotoAsync(int mesaId, String timestamp)
    {
        return _iceI_notificarVotoAsync(mesaId, timestamp, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notificarVotoAsync(int mesaId, String timestamp, java.util.Map<String, String> context)
    {
        return _iceI_notificarVotoAsync(mesaId, timestamp, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param iceP_timestamp -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notificarVotoAsync(int iceP_mesaId, String iceP_timestamp, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notificarVoto", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                     ostr.writeString(iceP_timestamp);
                 }, null);
        return f;
    }

    default void notificarError(int mesaId, String error)
    {
        notificarError(mesaId, error, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notificarError(int mesaId, String error, java.util.Map<String, String> context)
    {
        _iceI_notificarErrorAsync(mesaId, error, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notificarErrorAsync(int mesaId, String error)
    {
        return _iceI_notificarErrorAsync(mesaId, error, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notificarErrorAsync(int mesaId, String error, java.util.Map<String, String> context)
    {
        return _iceI_notificarErrorAsync(mesaId, error, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param iceP_error -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notificarErrorAsync(int iceP_mesaId, String iceP_error, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notificarError", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                     ostr.writeString(iceP_error);
                 }, null);
        return f;
    }

    default void notificarAlerta(int mesaId, String alerta)
    {
        notificarAlerta(mesaId, alerta, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notificarAlerta(int mesaId, String alerta, java.util.Map<String, String> context)
    {
        _iceI_notificarAlertaAsync(mesaId, alerta, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notificarAlertaAsync(int mesaId, String alerta)
    {
        return _iceI_notificarAlertaAsync(mesaId, alerta, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notificarAlertaAsync(int mesaId, String alerta, java.util.Map<String, String> context)
    {
        return _iceI_notificarAlertaAsync(mesaId, alerta, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param iceP_alerta -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notificarAlertaAsync(int iceP_mesaId, String iceP_alerta, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notificarAlerta", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                     ostr.writeString(iceP_alerta);
                 }, null);
        return f;
    }

    default void notificarCambioEstado(int mesaId, String nuevoEstado)
    {
        notificarCambioEstado(mesaId, nuevoEstado, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notificarCambioEstado(int mesaId, String nuevoEstado, java.util.Map<String, String> context)
    {
        _iceI_notificarCambioEstadoAsync(mesaId, nuevoEstado, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notificarCambioEstadoAsync(int mesaId, String nuevoEstado)
    {
        return _iceI_notificarCambioEstadoAsync(mesaId, nuevoEstado, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notificarCambioEstadoAsync(int mesaId, String nuevoEstado, java.util.Map<String, String> context)
    {
        return _iceI_notificarCambioEstadoAsync(mesaId, nuevoEstado, context, false);
    }

    /**
     * @hidden
     * @param iceP_mesaId -
     * @param iceP_nuevoEstado -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notificarCambioEstadoAsync(int iceP_mesaId, String iceP_nuevoEstado, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notificarCambioEstado", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_mesaId);
                     ostr.writeString(iceP_nuevoEstado);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StationNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), StationNotifierPrx.class, _StationNotifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StationNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), StationNotifierPrx.class, _StationNotifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StationNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), StationNotifierPrx.class, _StationNotifierPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StationNotifierPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), StationNotifierPrx.class, _StationNotifierPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static StationNotifierPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, StationNotifierPrx.class, _StationNotifierPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static StationNotifierPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, StationNotifierPrx.class, _StationNotifierPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default StationNotifierPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (StationNotifierPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default StationNotifierPrx ice_adapterId(String newAdapterId)
    {
        return (StationNotifierPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default StationNotifierPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (StationNotifierPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default StationNotifierPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (StationNotifierPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default StationNotifierPrx ice_invocationTimeout(int newTimeout)
    {
        return (StationNotifierPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default StationNotifierPrx ice_connectionCached(boolean newCache)
    {
        return (StationNotifierPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default StationNotifierPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (StationNotifierPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default StationNotifierPrx ice_secure(boolean b)
    {
        return (StationNotifierPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default StationNotifierPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (StationNotifierPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default StationNotifierPrx ice_preferSecure(boolean b)
    {
        return (StationNotifierPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default StationNotifierPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (StationNotifierPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default StationNotifierPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (StationNotifierPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default StationNotifierPrx ice_collocationOptimized(boolean b)
    {
        return (StationNotifierPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default StationNotifierPrx ice_twoway()
    {
        return (StationNotifierPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default StationNotifierPrx ice_oneway()
    {
        return (StationNotifierPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default StationNotifierPrx ice_batchOneway()
    {
        return (StationNotifierPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default StationNotifierPrx ice_datagram()
    {
        return (StationNotifierPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default StationNotifierPrx ice_batchDatagram()
    {
        return (StationNotifierPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default StationNotifierPrx ice_compress(boolean co)
    {
        return (StationNotifierPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default StationNotifierPrx ice_timeout(int t)
    {
        return (StationNotifierPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default StationNotifierPrx ice_connectionId(String connectionId)
    {
        return (StationNotifierPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default StationNotifierPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (StationNotifierPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::VotingSystem::StationNotifier";
    }
}
