//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MainServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public interface VoteStationPrx extends com.zeroc.Ice.ObjectPrx
{
    default int registrarVoto(String documento, int candidatoId)
    {
        return registrarVoto(documento, candidatoId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int registrarVoto(String documento, int candidatoId, java.util.Map<String, String> context)
    {
        return _iceI_registrarVotoAsync(documento, candidatoId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> registrarVotoAsync(String documento, int candidatoId)
    {
        return _iceI_registrarVotoAsync(documento, candidatoId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> registrarVotoAsync(String documento, int candidatoId, java.util.Map<String, String> context)
    {
        return _iceI_registrarVotoAsync(documento, candidatoId, context, false);
    }

    /**
     * @hidden
     * @param iceP_documento -
     * @param iceP_candidatoId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_registrarVotoAsync(String iceP_documento, int iceP_candidatoId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registrarVoto", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_documento);
                     ostr.writeInt(iceP_candidatoId);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default boolean validarVotante(String documento)
    {
        return validarVotante(documento, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean validarVotante(String documento, java.util.Map<String, String> context)
    {
        return _iceI_validarVotanteAsync(documento, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> validarVotanteAsync(String documento)
    {
        return _iceI_validarVotanteAsync(documento, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> validarVotanteAsync(String documento, java.util.Map<String, String> context)
    {
        return _iceI_validarVotanteAsync(documento, context, false);
    }

    /**
     * @hidden
     * @param iceP_documento -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_validarVotanteAsync(String iceP_documento, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "validarVotante", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_documento);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default String obtenerEstadoEstacion()
    {
        return obtenerEstadoEstacion(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String obtenerEstadoEstacion(java.util.Map<String, String> context)
    {
        return _iceI_obtenerEstadoEstacionAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> obtenerEstadoEstacionAsync()
    {
        return _iceI_obtenerEstadoEstacionAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> obtenerEstadoEstacionAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerEstadoEstacionAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_obtenerEstadoEstacionAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerEstadoEstacion", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void cerrarEstacion()
    {
        cerrarEstacion(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void cerrarEstacion(java.util.Map<String, String> context)
    {
        _iceI_cerrarEstacionAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> cerrarEstacionAsync()
    {
        return _iceI_cerrarEstacionAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> cerrarEstacionAsync(java.util.Map<String, String> context)
    {
        return _iceI_cerrarEstacionAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_cerrarEstacionAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "cerrarEstacion", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default int obtenerTotalVotosEstacion()
    {
        return obtenerTotalVotosEstacion(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int obtenerTotalVotosEstacion(java.util.Map<String, String> context)
    {
        return _iceI_obtenerTotalVotosEstacionAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> obtenerTotalVotosEstacionAsync()
    {
        return _iceI_obtenerTotalVotosEstacionAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> obtenerTotalVotosEstacionAsync(java.util.Map<String, String> context)
    {
        return _iceI_obtenerTotalVotosEstacionAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_obtenerTotalVotosEstacionAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "obtenerTotalVotosEstacion", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoteStationPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), VoteStationPrx.class, _VoteStationPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoteStationPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), VoteStationPrx.class, _VoteStationPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoteStationPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), VoteStationPrx.class, _VoteStationPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoteStationPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), VoteStationPrx.class, _VoteStationPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static VoteStationPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, VoteStationPrx.class, _VoteStationPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static VoteStationPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, VoteStationPrx.class, _VoteStationPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default VoteStationPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (VoteStationPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default VoteStationPrx ice_adapterId(String newAdapterId)
    {
        return (VoteStationPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default VoteStationPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (VoteStationPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default VoteStationPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (VoteStationPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default VoteStationPrx ice_invocationTimeout(int newTimeout)
    {
        return (VoteStationPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default VoteStationPrx ice_connectionCached(boolean newCache)
    {
        return (VoteStationPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default VoteStationPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (VoteStationPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default VoteStationPrx ice_secure(boolean b)
    {
        return (VoteStationPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default VoteStationPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (VoteStationPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default VoteStationPrx ice_preferSecure(boolean b)
    {
        return (VoteStationPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default VoteStationPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (VoteStationPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default VoteStationPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (VoteStationPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default VoteStationPrx ice_collocationOptimized(boolean b)
    {
        return (VoteStationPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default VoteStationPrx ice_twoway()
    {
        return (VoteStationPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default VoteStationPrx ice_oneway()
    {
        return (VoteStationPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default VoteStationPrx ice_batchOneway()
    {
        return (VoteStationPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default VoteStationPrx ice_datagram()
    {
        return (VoteStationPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default VoteStationPrx ice_batchDatagram()
    {
        return (VoteStationPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default VoteStationPrx ice_compress(boolean co)
    {
        return (VoteStationPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default VoteStationPrx ice_timeout(int t)
    {
        return (VoteStationPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default VoteStationPrx ice_connectionId(String connectionId)
    {
        return (VoteStationPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default VoteStationPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (VoteStationPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::VotingSystem::VoteStation";
    }
}
