//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReliableMsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.reliablemsg.ReliableMsg;

public interface _VotoQueueOperations
{
    void enviarComando(String comando, Ice.Current current);

    String getVoto(Ice.Current current);

    void publicarEvento(String evento, Ice.Current current);
}
