//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReliableMsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.reliablemsg.ReliableMsg;

public class _VotoQueueTie extends _VotoQueueDisp implements Ice.TieBase
{
    public _VotoQueueTie()
    {
    }

    public _VotoQueueTie(_VotoQueueOperations delegate)
    {
        _ice_delegate = delegate;
    }

    public java.lang.Object ice_delegate()
    {
        return _ice_delegate;
    }

    public void ice_delegate(java.lang.Object delegate)
    {
        _ice_delegate = (_VotoQueueOperations)delegate;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        if(!(rhs instanceof _VotoQueueTie))
        {
            return false;
        }

        return _ice_delegate.equals(((_VotoQueueTie)rhs)._ice_delegate);
    }

    public int hashCode()
    {
        return _ice_delegate.hashCode();
    }

    public void enviarComando(String comando, Ice.Current current)
    {
        _ice_delegate.enviarComando(comando, current);
    }

    public String getVoto(Ice.Current current)
    {
        return _ice_delegate.getVoto(current);
    }

    public void publicarEvento(String evento, Ice.Current current)
    {
        _ice_delegate.publicarEvento(evento, current);
    }

    private _VotoQueueOperations _ice_delegate;

    public static final long serialVersionUID = 6895462598896076495L;
}
