//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReliableMsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.reliablemsg.ReliableMsg;

public abstract class _VotoQueueDisp extends Ice.ObjectImpl implements VotoQueue
{
    private static final String[] _ids =
    {
        "::Ice::Object",
        "::ReliableMsg::VotoQueue"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(_ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current current)
    {
        return java.util.Arrays.binarySearch(_ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return _ids;
    }

    public String[] ice_ids(Ice.Current current)
    {
        return _ids;
    }

    public String ice_id()
    {
        return _ids[1];
    }

    public String ice_id(Ice.Current current)
    {
        return _ids[1];
    }

    public static String ice_staticId()
    {
        return _ids[1];
    }

    public final void enviarComando(String comando)
    {
        enviarComando(comando, null);
    }

    public final String getVoto()
    {
        return getVoto(null);
    }

    public final void publicarEvento(String evento)
    {
        publicarEvento(evento, null);
    }

    public static boolean _iceD_enviarComando(VotoQueue obj, IceInternal.Incoming inS, Ice.Current current)
        throws Ice.UserException
    {
        _iceCheckMode(Ice.OperationMode.Normal, current.mode);
        Ice.InputStream istr = inS.startReadParams();
        String iceP_comando;
        iceP_comando = istr.readString();
        inS.endReadParams();
        obj.enviarComando(iceP_comando, current);
        inS.writeEmptyParams();
        return true;
    }

    public static boolean _iceD_getVoto(VotoQueue obj, IceInternal.Incoming inS, Ice.Current current)
        throws Ice.UserException
    {
        _iceCheckMode(Ice.OperationMode.Normal, current.mode);
        inS.readEmptyParams();
        String ret = obj.getVoto(current);
        Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams();
        return true;
    }

    public static boolean _iceD_publicarEvento(VotoQueue obj, IceInternal.Incoming inS, Ice.Current current)
        throws Ice.UserException
    {
        _iceCheckMode(Ice.OperationMode.Normal, current.mode);
        Ice.InputStream istr = inS.startReadParams();
        String iceP_evento;
        iceP_evento = istr.readString();
        inS.endReadParams();
        obj.publicarEvento(iceP_evento, current);
        inS.writeEmptyParams();
        return true;
    }

    private final static String[] _all =
    {
        "enviarComando",
        "getVoto",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "publicarEvento"
    };

    public boolean _iceDispatch(IceInternal.Incoming in, Ice.Current current)
        throws Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_all, current.operation);
        if(pos < 0)
        {
            throw new Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_enviarComando(this, in, current);
            }
            case 1:
            {
                return _iceD_getVoto(this, in, current);
            }
            case 2:
            {
                return _iceD_ice_id(this, in, current);
            }
            case 3:
            {
                return _iceD_ice_ids(this, in, current);
            }
            case 4:
            {
                return _iceD_ice_isA(this, in, current);
            }
            case 5:
            {
                return _iceD_ice_ping(this, in, current);
            }
            case 6:
            {
                return _iceD_publicarEvento(this, in, current);
            }
        }

        assert(false);
        throw new Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }

    protected void _iceWriteImpl(Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.endSlice();
    }

    protected void _iceReadImpl(Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
    }

    public static final long serialVersionUID = 0L;
}
