//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReliableMsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.reliablemsg.ReliableMsg;

public abstract class Callback_VotoQueue_getVoto
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<String>
{
    public final void _iceCompleted(Ice.AsyncResult result)
    {
        VotoQueuePrxHelper._iceI_getVoto_completed(this, result);
    }
}
