//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReliableMsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.reliablemsg.ReliableMsg;

public interface VotoQueue extends _VotoQueueOperations, _VotoQueueOperationsNC,
                                   Ice.Object
{
    public static final String ice_staticId = "::ReliableMsg::VotoQueue";

    public static final long serialVersionUID = 6895462598896076495L;
}
