//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReliableMsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.reliablemsg.ReliableMsg;

public final class VotoQueuePrxHolder
{
    public
    VotoQueuePrxHolder()
    {
    }

    public
    VotoQueuePrxHolder(VotoQueuePrx value)
    {
        this.value = value;
    }

    public VotoQueuePrx value;
}
