//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReliableMsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.reliablemsg.ReliableMsg;

public final class VotoQueueHolder extends Ice.ObjectHolderBase<VotoQueue>
{
    public
    VotoQueueHolder()
    {
    }

    public
    VotoQueueHolder(VotoQueue value)
    {
        this.value = value;
    }

    public void
    valueReady(Ice.Object v)
    {
        if(v == null || v instanceof VotoQueue)
        {
            value = (VotoQueue)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _VotoQueueDisp.ice_staticId();
    }
}
