//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReliableMsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.reliablemsg.ReliableMsg;

public interface VotoQueuePrx extends Ice.ObjectPrx
{
    public void enviarComando(String comando);

    public void enviarComando(String comando, java.util.Map<String, String> context);

    public Ice.AsyncResult begin_enviarComando(String comando);

    public Ice.AsyncResult begin_enviarComando(String comando, java.util.Map<String, String> context);

    public Ice.AsyncResult begin_enviarComando(String comando, Ice.Callback cb);

    public Ice.AsyncResult begin_enviarComando(String comando, java.util.Map<String, String> context, Ice.Callback cb);

    public Ice.AsyncResult begin_enviarComando(String comando, Callback_VotoQueue_enviarComando cb);

    public Ice.AsyncResult begin_enviarComando(String comando, java.util.Map<String, String> context, Callback_VotoQueue_enviarComando cb);

    public Ice.AsyncResult begin_enviarComando(String comando,
                                               IceInternal.Functional_VoidCallback responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb);

    public Ice.AsyncResult begin_enviarComando(String comando,
                                               IceInternal.Functional_VoidCallback responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                               IceInternal.Functional_BoolCallback sentCb);

    public Ice.AsyncResult begin_enviarComando(String comando,
                                               java.util.Map<String, String> context,
                                               IceInternal.Functional_VoidCallback responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb);

    public Ice.AsyncResult begin_enviarComando(String comando,
                                               java.util.Map<String, String> context,
                                               IceInternal.Functional_VoidCallback responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                               IceInternal.Functional_BoolCallback sentCb);

    public void end_enviarComando(Ice.AsyncResult result);

    public String getVoto();

    public String getVoto(java.util.Map<String, String> context);

    public Ice.AsyncResult begin_getVoto();

    public Ice.AsyncResult begin_getVoto(java.util.Map<String, String> context);

    public Ice.AsyncResult begin_getVoto(Ice.Callback cb);

    public Ice.AsyncResult begin_getVoto(java.util.Map<String, String> context, Ice.Callback cb);

    public Ice.AsyncResult begin_getVoto(Callback_VotoQueue_getVoto cb);

    public Ice.AsyncResult begin_getVoto(java.util.Map<String, String> context, Callback_VotoQueue_getVoto cb);

    public Ice.AsyncResult begin_getVoto(IceInternal.Functional_GenericCallback1<String> responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb);

    public Ice.AsyncResult begin_getVoto(IceInternal.Functional_GenericCallback1<String> responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                         IceInternal.Functional_BoolCallback sentCb);

    public Ice.AsyncResult begin_getVoto(java.util.Map<String, String> context,
                                         IceInternal.Functional_GenericCallback1<String> responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb);

    public Ice.AsyncResult begin_getVoto(java.util.Map<String, String> context,
                                         IceInternal.Functional_GenericCallback1<String> responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                         IceInternal.Functional_BoolCallback sentCb);

    public String end_getVoto(Ice.AsyncResult result);

    public void publicarEvento(String evento);

    public void publicarEvento(String evento, java.util.Map<String, String> context);

    public Ice.AsyncResult begin_publicarEvento(String evento);

    public Ice.AsyncResult begin_publicarEvento(String evento, java.util.Map<String, String> context);

    public Ice.AsyncResult begin_publicarEvento(String evento, Ice.Callback cb);

    public Ice.AsyncResult begin_publicarEvento(String evento, java.util.Map<String, String> context, Ice.Callback cb);

    public Ice.AsyncResult begin_publicarEvento(String evento, Callback_VotoQueue_publicarEvento cb);

    public Ice.AsyncResult begin_publicarEvento(String evento, java.util.Map<String, String> context, Callback_VotoQueue_publicarEvento cb);

    public Ice.AsyncResult begin_publicarEvento(String evento,
                                                IceInternal.Functional_VoidCallback responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb);

    public Ice.AsyncResult begin_publicarEvento(String evento,
                                                IceInternal.Functional_VoidCallback responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                                IceInternal.Functional_BoolCallback sentCb);

    public Ice.AsyncResult begin_publicarEvento(String evento,
                                                java.util.Map<String, String> context,
                                                IceInternal.Functional_VoidCallback responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb);

    public Ice.AsyncResult begin_publicarEvento(String evento,
                                                java.util.Map<String, String> context,
                                                IceInternal.Functional_VoidCallback responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                                IceInternal.Functional_BoolCallback sentCb);

    public void end_publicarEvento(Ice.AsyncResult result);
}
