//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ReliableMsg.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sistemaelectoral.reliablemsg.ReliableMsg;

/**
 * Provides type-specific helper functions.
 **/
public final class VotoQueuePrxHelper extends Ice.ObjectPrxHelperBase implements VotoQueuePrx
{
    private static final String _enviarComando_name = "enviarComando";

    public void enviarComando(String comando)
    {
        _iceI_enviarComando(comando, null, false);
    }

    public void enviarComando(String comando, java.util.Map<String, String> context)
    {
        _iceI_enviarComando(comando, context, true);
    }

    private void _iceI_enviarComando(String iceP_comando, java.util.Map<String, String> context, boolean explicitCtx)
    {
        end_enviarComando(_iceI_begin_enviarComando(iceP_comando, context, explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_enviarComando(String comando)
    {
        return _iceI_begin_enviarComando(comando, null, false, false, null);
    }

    public Ice.AsyncResult begin_enviarComando(String comando, java.util.Map<String, String> context)
    {
        return _iceI_begin_enviarComando(comando, context, true, false, null);
    }

    public Ice.AsyncResult begin_enviarComando(String comando, Ice.Callback cb)
    {
        return _iceI_begin_enviarComando(comando, null, false, false, cb);
    }

    public Ice.AsyncResult begin_enviarComando(String comando, java.util.Map<String, String> context, Ice.Callback cb)
    {
        return _iceI_begin_enviarComando(comando, context, true, false, cb);
    }

    public Ice.AsyncResult begin_enviarComando(String comando, Callback_VotoQueue_enviarComando cb)
    {
        return _iceI_begin_enviarComando(comando, null, false, false, cb);
    }

    public Ice.AsyncResult begin_enviarComando(String comando, java.util.Map<String, String> context, Callback_VotoQueue_enviarComando cb)
    {
        return _iceI_begin_enviarComando(comando, context, true, false, cb);
    }

    public Ice.AsyncResult begin_enviarComando(String comando,
                                               IceInternal.Functional_VoidCallback responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb)
    {
        return _iceI_begin_enviarComando(comando, null, false, false, responseCb, exceptionCb, null);
    }

    public Ice.AsyncResult begin_enviarComando(String comando,
                                               IceInternal.Functional_VoidCallback responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                               IceInternal.Functional_BoolCallback sentCb)
    {
        return _iceI_begin_enviarComando(comando, null, false, false, responseCb, exceptionCb, sentCb);
    }

    public Ice.AsyncResult begin_enviarComando(String comando,
                                               java.util.Map<String, String> context,
                                               IceInternal.Functional_VoidCallback responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb)
    {
        return _iceI_begin_enviarComando(comando, context, true, false, responseCb, exceptionCb, null);
    }

    public Ice.AsyncResult begin_enviarComando(String comando,
                                               java.util.Map<String, String> context,
                                               IceInternal.Functional_VoidCallback responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                               IceInternal.Functional_BoolCallback sentCb)
    {
        return _iceI_begin_enviarComando(comando, context, true, false, responseCb, exceptionCb, sentCb);
    }

    private Ice.AsyncResult _iceI_begin_enviarComando(String iceP_comando,
                                                      java.util.Map<String, String> context,
                                                      boolean explicitCtx,
                                                      boolean synchronous,
                                                      IceInternal.Functional_VoidCallback responseCb,
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                                      IceInternal.Functional_BoolCallback sentCb)
    {
        return _iceI_begin_enviarComando(iceP_comando,
                                         context,
                                         explicitCtx,
                                         synchronous,
                                         new IceInternal.Functional_OnewayCallback(responseCb, exceptionCb, sentCb));
    }

    private Ice.AsyncResult _iceI_begin_enviarComando(String iceP_comando,
                                                      java.util.Map<String, String> context,
                                                      boolean explicitCtx,
                                                      boolean synchronous,
                                                      IceInternal.CallbackBase cb)
    {
        IceInternal.OutgoingAsync result = getOutgoingAsync(_enviarComando_name, cb);
        try
        {
            result.prepare(_enviarComando_name, Ice.OperationMode.Normal, context, explicitCtx, synchronous);
            Ice.OutputStream ostr = result.startWriteParams(Ice.FormatType.DefaultFormat);
            ostr.writeString(iceP_comando);
            result.endWriteParams();
            result.invoke();
        }
        catch(Ice.Exception ex)
        {
            result.abort(ex);
        }
        return result;
    }

    public void end_enviarComando(Ice.AsyncResult iresult)
    {
        _end(iresult, _enviarComando_name);
    }

    private static final String _getVoto_name = "getVoto";

    public String getVoto()
    {
        return _iceI_getVoto(null, false);
    }

    public String getVoto(java.util.Map<String, String> context)
    {
        return _iceI_getVoto(context, true);
    }

    private String _iceI_getVoto(java.util.Map<String, String> context, boolean explicitCtx)
    {
        _checkTwowayOnly(_getVoto_name);
        return end_getVoto(_iceI_begin_getVoto(context, explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_getVoto()
    {
        return _iceI_begin_getVoto(null, false, false, null);
    }

    public Ice.AsyncResult begin_getVoto(java.util.Map<String, String> context)
    {
        return _iceI_begin_getVoto(context, true, false, null);
    }

    public Ice.AsyncResult begin_getVoto(Ice.Callback cb)
    {
        return _iceI_begin_getVoto(null, false, false, cb);
    }

    public Ice.AsyncResult begin_getVoto(java.util.Map<String, String> context, Ice.Callback cb)
    {
        return _iceI_begin_getVoto(context, true, false, cb);
    }

    public Ice.AsyncResult begin_getVoto(Callback_VotoQueue_getVoto cb)
    {
        return _iceI_begin_getVoto(null, false, false, cb);
    }

    public Ice.AsyncResult begin_getVoto(java.util.Map<String, String> context, Callback_VotoQueue_getVoto cb)
    {
        return _iceI_begin_getVoto(context, true, false, cb);
    }

    public Ice.AsyncResult begin_getVoto(IceInternal.Functional_GenericCallback1<String> responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb)
    {
        return _iceI_begin_getVoto(null, false, false, responseCb, exceptionCb, null);
    }

    public Ice.AsyncResult begin_getVoto(IceInternal.Functional_GenericCallback1<String> responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                         IceInternal.Functional_BoolCallback sentCb)
    {
        return _iceI_begin_getVoto(null, false, false, responseCb, exceptionCb, sentCb);
    }

    public Ice.AsyncResult begin_getVoto(java.util.Map<String, String> context,
                                         IceInternal.Functional_GenericCallback1<String> responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb)
    {
        return _iceI_begin_getVoto(context, true, false, responseCb, exceptionCb, null);
    }

    public Ice.AsyncResult begin_getVoto(java.util.Map<String, String> context,
                                         IceInternal.Functional_GenericCallback1<String> responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                         IceInternal.Functional_BoolCallback sentCb)
    {
        return _iceI_begin_getVoto(context, true, false, responseCb, exceptionCb, sentCb);
    }

    private Ice.AsyncResult _iceI_begin_getVoto(java.util.Map<String, String> context,
                                                boolean explicitCtx,
                                                boolean synchronous,
                                                IceInternal.Functional_GenericCallback1<String> responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                                IceInternal.Functional_BoolCallback sentCb)
    {
        return _iceI_begin_getVoto(context,
                                   explicitCtx,
                                   synchronous,
                                   new IceInternal.Functional_TwowayCallbackArg1<String>(responseCb, exceptionCb, sentCb)
                                       {
                                           public final void _iceCompleted(Ice.AsyncResult result)
                                           {
                                               VotoQueuePrxHelper._iceI_getVoto_completed(this, result);
                                           }
                                       });
    }

    private Ice.AsyncResult _iceI_begin_getVoto(java.util.Map<String, String> context,
                                                boolean explicitCtx,
                                                boolean synchronous,
                                                IceInternal.CallbackBase cb)
    {
        _checkAsyncTwowayOnly(_getVoto_name);
        IceInternal.OutgoingAsync result = getOutgoingAsync(_getVoto_name, cb);
        try
        {
            result.prepare(_getVoto_name, Ice.OperationMode.Normal, context, explicitCtx, synchronous);
            result.writeEmptyParams();
            result.invoke();
        }
        catch(Ice.Exception ex)
        {
            result.abort(ex);
        }
        return result;
    }

    public String end_getVoto(Ice.AsyncResult iresult)
    {
        IceInternal.OutgoingAsync result_ = IceInternal.OutgoingAsync.check(iresult, this, _getVoto_name);
        try
        {
            if(!result_.waitForResponseOrUserEx())
            {
                try
                {
                    result_.throwUserException();
                }
                catch(Ice.UserException ex_)
                {
                    throw new Ice.UnknownUserException(ex_.ice_id(), ex_);
                }
            }
            Ice.InputStream istr_ = result_.startReadParams();
            String ret_;
            ret_ = istr_.readString();
            result_.endReadParams();
            return ret_;
        }
        finally
        {
            if(result_ != null)
            {
                result_.cacheMessageBuffers();
            }
        }
    }

    static public void _iceI_getVoto_completed(Ice.TwowayCallbackArg1<String> cb, Ice.AsyncResult result)
    {
        com.sistemaelectoral.reliablemsg.ReliableMsg.VotoQueuePrx _proxy = (com.sistemaelectoral.reliablemsg.ReliableMsg.VotoQueuePrx)result.getProxy();
        String ret = null;
        try
        {
            ret = _proxy.end_getVoto(result);
        }
        catch(Ice.LocalException ex)
        {
            cb.exception(ex);
            return;
        }
        catch(Ice.SystemException ex)
        {
            cb.exception(ex);
            return;
        }
        cb.response(ret);
    }

    private static final String _publicarEvento_name = "publicarEvento";

    public void publicarEvento(String evento)
    {
        _iceI_publicarEvento(evento, null, false);
    }

    public void publicarEvento(String evento, java.util.Map<String, String> context)
    {
        _iceI_publicarEvento(evento, context, true);
    }

    private void _iceI_publicarEvento(String iceP_evento, java.util.Map<String, String> context, boolean explicitCtx)
    {
        end_publicarEvento(_iceI_begin_publicarEvento(iceP_evento, context, explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_publicarEvento(String evento)
    {
        return _iceI_begin_publicarEvento(evento, null, false, false, null);
    }

    public Ice.AsyncResult begin_publicarEvento(String evento, java.util.Map<String, String> context)
    {
        return _iceI_begin_publicarEvento(evento, context, true, false, null);
    }

    public Ice.AsyncResult begin_publicarEvento(String evento, Ice.Callback cb)
    {
        return _iceI_begin_publicarEvento(evento, null, false, false, cb);
    }

    public Ice.AsyncResult begin_publicarEvento(String evento, java.util.Map<String, String> context, Ice.Callback cb)
    {
        return _iceI_begin_publicarEvento(evento, context, true, false, cb);
    }

    public Ice.AsyncResult begin_publicarEvento(String evento, Callback_VotoQueue_publicarEvento cb)
    {
        return _iceI_begin_publicarEvento(evento, null, false, false, cb);
    }

    public Ice.AsyncResult begin_publicarEvento(String evento, java.util.Map<String, String> context, Callback_VotoQueue_publicarEvento cb)
    {
        return _iceI_begin_publicarEvento(evento, context, true, false, cb);
    }

    public Ice.AsyncResult begin_publicarEvento(String evento,
                                                IceInternal.Functional_VoidCallback responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb)
    {
        return _iceI_begin_publicarEvento(evento, null, false, false, responseCb, exceptionCb, null);
    }

    public Ice.AsyncResult begin_publicarEvento(String evento,
                                                IceInternal.Functional_VoidCallback responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                                IceInternal.Functional_BoolCallback sentCb)
    {
        return _iceI_begin_publicarEvento(evento, null, false, false, responseCb, exceptionCb, sentCb);
    }

    public Ice.AsyncResult begin_publicarEvento(String evento,
                                                java.util.Map<String, String> context,
                                                IceInternal.Functional_VoidCallback responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb)
    {
        return _iceI_begin_publicarEvento(evento, context, true, false, responseCb, exceptionCb, null);
    }

    public Ice.AsyncResult begin_publicarEvento(String evento,
                                                java.util.Map<String, String> context,
                                                IceInternal.Functional_VoidCallback responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                                IceInternal.Functional_BoolCallback sentCb)
    {
        return _iceI_begin_publicarEvento(evento, context, true, false, responseCb, exceptionCb, sentCb);
    }

    private Ice.AsyncResult _iceI_begin_publicarEvento(String iceP_evento,
                                                       java.util.Map<String, String> context,
                                                       boolean explicitCtx,
                                                       boolean synchronous,
                                                       IceInternal.Functional_VoidCallback responseCb,
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> exceptionCb,
                                                       IceInternal.Functional_BoolCallback sentCb)
    {
        return _iceI_begin_publicarEvento(iceP_evento,
                                          context,
                                          explicitCtx,
                                          synchronous,
                                          new IceInternal.Functional_OnewayCallback(responseCb, exceptionCb, sentCb));
    }

    private Ice.AsyncResult _iceI_begin_publicarEvento(String iceP_evento,
                                                       java.util.Map<String, String> context,
                                                       boolean explicitCtx,
                                                       boolean synchronous,
                                                       IceInternal.CallbackBase cb)
    {
        IceInternal.OutgoingAsync result = getOutgoingAsync(_publicarEvento_name, cb);
        try
        {
            result.prepare(_publicarEvento_name, Ice.OperationMode.Normal, context, explicitCtx, synchronous);
            Ice.OutputStream ostr = result.startWriteParams(Ice.FormatType.DefaultFormat);
            ostr.writeString(iceP_evento);
            result.endWriteParams();
            result.invoke();
        }
        catch(Ice.Exception ex)
        {
            result.abort(ex);
        }
        return result;
    }

    public void end_publicarEvento(Ice.AsyncResult iresult)
    {
        _end(iresult, _publicarEvento_name);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static VotoQueuePrx checkedCast(Ice.ObjectPrx obj)
    {
        return checkedCastImpl(obj, ice_staticId(), VotoQueuePrx.class, VotoQueuePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static VotoQueuePrx checkedCast(Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return checkedCastImpl(obj, context, ice_staticId(), VotoQueuePrx.class, VotoQueuePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static VotoQueuePrx checkedCast(Ice.ObjectPrx obj, String facet)
    {
        return checkedCastImpl(obj, facet, ice_staticId(), VotoQueuePrx.class, VotoQueuePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static VotoQueuePrx checkedCast(Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return checkedCastImpl(obj, facet, context, ice_staticId(), VotoQueuePrx.class, VotoQueuePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static VotoQueuePrx uncheckedCast(Ice.ObjectPrx obj)
    {
        return uncheckedCastImpl(obj, VotoQueuePrx.class, VotoQueuePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static VotoQueuePrx uncheckedCast(Ice.ObjectPrx obj, String facet)
    {
        return uncheckedCastImpl(obj, facet, VotoQueuePrx.class, VotoQueuePrxHelper.class);
    }

    private static final String[] _ids =
    {
        "::Ice::Object",
        "::ReliableMsg::VotoQueue"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return _ids[1];
    }

    public static void write(Ice.OutputStream ostr, VotoQueuePrx v)
    {
        ostr.writeProxy(v);
    }

    public static VotoQueuePrx read(Ice.InputStream istr)
    {
        Ice.ObjectPrx proxy = istr.readProxy();
        if(proxy != null)
        {
            VotoQueuePrxHelper result = new VotoQueuePrxHelper();
            result._copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
