# Configuración de Supabase
Supabase.URL=https://tciviopfpcxqrbcnoovq.supabase.co
Supabase.Key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjaXZpb3BmcGN4cXJiY25vb3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDI3NTIsImV4cCI6MjA2NDM3ODc1Mn0.JmD6M9XOM9VJdMYF7Aq4PW7wkXPX4UjJa7mBO27Dcvw

# Configuración de tablas de la base de datos
Database.Tables.Ciudadanos=ciudadanos
Database.Tables.ZonasVotacion=zonas_votacion
Database.Tables.CiudadanosMesaZonaAsignada=ciudadanos_mesa_zona_asignada
Database.Tables.Candidatos=candidatos
Database.Tables.Votos=votos
Database.Tables.Resultados=resultados
Database.Tables.Formulario=formulario
Database.Tables.Sospechosos=sospechosos
Database.Tables.AuditoriaLogs=auditoria_logs
Database.Tables.Usuarios=usuarios
Database.Tables.Tokens=tokens
Database.Tables.Permisos=permisos

# Configuración de Ice
Ice.Default.Locator=IceGrid/Locator -t:tcp -h localhost -p 4061
Ice.Default.Protocol=tcp 