//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `SecurityModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SecurityModule;

public interface SecurityServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default boolean validateSecurity(String document)
    {
        return validateSecurity(document, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean validateSecurity(String document, java.util.Map<String, String> context)
    {
        return _iceI_validateSecurityAsync(document, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> validateSecurityAsync(String document)
    {
        return _iceI_validateSecurityAsync(document, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> validateSecurityAsync(String document, java.util.Map<String, String> context)
    {
        return _iceI_validateSecurityAsync(document, context, false);
    }

    /**
     * @hidden
     * @param iceP_document -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_validateSecurityAsync(String iceP_document, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "validateSecurity", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_document);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean checkVotingStatus(String document)
    {
        return checkVotingStatus(document, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean checkVotingStatus(String document, java.util.Map<String, String> context)
    {
        return _iceI_checkVotingStatusAsync(document, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> checkVotingStatusAsync(String document)
    {
        return _iceI_checkVotingStatusAsync(document, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> checkVotingStatusAsync(String document, java.util.Map<String, String> context)
    {
        return _iceI_checkVotingStatusAsync(document, context, false);
    }

    /**
     * @hidden
     * @param iceP_document -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_checkVotingStatusAsync(String iceP_document, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "checkVotingStatus", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_document);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean validateMesaZonaAsignada(String document, int mesaId, int zonaId)
    {
        return validateMesaZonaAsignada(document, mesaId, zonaId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean validateMesaZonaAsignada(String document, int mesaId, int zonaId, java.util.Map<String, String> context)
    {
        return _iceI_validateMesaZonaAsignadaAsync(document, mesaId, zonaId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> validateMesaZonaAsignadaAsync(String document, int mesaId, int zonaId)
    {
        return _iceI_validateMesaZonaAsignadaAsync(document, mesaId, zonaId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> validateMesaZonaAsignadaAsync(String document, int mesaId, int zonaId, java.util.Map<String, String> context)
    {
        return _iceI_validateMesaZonaAsignadaAsync(document, mesaId, zonaId, context, false);
    }

    /**
     * @hidden
     * @param iceP_document -
     * @param iceP_mesaId -
     * @param iceP_zonaId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_validateMesaZonaAsignadaAsync(String iceP_document, int iceP_mesaId, int iceP_zonaId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "validateMesaZonaAsignada", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_document);
                     ostr.writeInt(iceP_mesaId);
                     ostr.writeInt(iceP_zonaId);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SecurityServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), SecurityServicePrx.class, _SecurityServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SecurityServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), SecurityServicePrx.class, _SecurityServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SecurityServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), SecurityServicePrx.class, _SecurityServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SecurityServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), SecurityServicePrx.class, _SecurityServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static SecurityServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, SecurityServicePrx.class, _SecurityServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static SecurityServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, SecurityServicePrx.class, _SecurityServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default SecurityServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (SecurityServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default SecurityServicePrx ice_adapterId(String newAdapterId)
    {
        return (SecurityServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default SecurityServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (SecurityServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default SecurityServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (SecurityServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default SecurityServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (SecurityServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default SecurityServicePrx ice_connectionCached(boolean newCache)
    {
        return (SecurityServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default SecurityServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (SecurityServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SecurityServicePrx ice_secure(boolean b)
    {
        return (SecurityServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default SecurityServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (SecurityServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SecurityServicePrx ice_preferSecure(boolean b)
    {
        return (SecurityServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default SecurityServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (SecurityServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default SecurityServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (SecurityServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default SecurityServicePrx ice_collocationOptimized(boolean b)
    {
        return (SecurityServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default SecurityServicePrx ice_twoway()
    {
        return (SecurityServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default SecurityServicePrx ice_oneway()
    {
        return (SecurityServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default SecurityServicePrx ice_batchOneway()
    {
        return (SecurityServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default SecurityServicePrx ice_datagram()
    {
        return (SecurityServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default SecurityServicePrx ice_batchDatagram()
    {
        return (SecurityServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default SecurityServicePrx ice_compress(boolean co)
    {
        return (SecurityServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default SecurityServicePrx ice_timeout(int t)
    {
        return (SecurityServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default SecurityServicePrx ice_connectionId(String connectionId)
    {
        return (SecurityServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default SecurityServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (SecurityServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SecurityModule::SecurityService";
    }
}
